### ISSUE TITLE
Cannot remap root ELF with overlapping sections

### ISSUE THREAD

**Issue by ghost** [alex-ab/NOVA#4]
As far as I can tell NOVA cannot remap the root ELF into the root EC if some sections have an ELF region that is small than their logical size in memory. This is sometimes the case when I build and link a Genode core image using Clang.

https://github.com/alex-ab/NOVA/blob/792d13135e31af9c3739eb067213314ed7721925/src/ec.cpp#L279

Is it reasonable to make copies of these sections where they cannot be directly delegated, or does this need to be fixed during linking the root image?

**Comment by alex-ab** [comment]
The kernel does not support it since the birth intentionally, mainly because of bureaucracy overhead (finding memory for the range between f_size->m_size, zeroing it out, decision/policy from where the range should be taken etc pp.). Long story short, a roottask must be linked such that all pt_load segments are f_size == m_size

**Comment by ghost** [comment]
Thats reasonable, I will try tweaking the linking then.
